### PR TITLE
Issues #6, #7 - Adding 0.9 capabilities, auto-retrieval of orgId. Started implementation of ServerCloneApi

### PR DESCRIPTION
**Pull request by trevorflanagan**
Issues #6, #7 - Adding 0.9 capabilities, auto-retrieval of orgId. Started implementation of ServerCloneApi

### CODE REVIEW

**Comment by andreaturli** [comment]
thanks @trevorflanagan great start!

have you considered `@RequestFilters` to manipulate the request so that you can inject the orgId in the path? In jclouds, it is generally used for Authentication purposes, like in DD at https://github.com/cloudsoft/amp-dimensiondata/blob/23262879b585b2f8d639c6254c6f2ffd37cad6a0/src/main/java/org/jclouds/dimensiondata/cloudcontroller/features/InfrastructureApi.java#L40-L40, but I guess you could add another HttpRequestFilter which injects the right orgId just before the request is sent.

This seems a quick win to me, wdyt?

**Comment by trevorflanagan** [comment]
thanks @andreaturli that simplifies things nicely. I have gone with the following approach, there is one side effect that I don't really like but maybe it is something we live with.

`@RequestFilters({BasicAuthentication.class, OrganisationIdFilter.class})
@Consumes(MediaType.APPLICATION_XML)
@Path("/oec/0.9/ORG-ID")
public interface ServerCloneApi`

In my new OrganisationIdFilter class I replace the endpoint details by doing a replace of ORG-ID. I originally thought about leaving {org-id} and replacing that but intellij warns about this.

The one issue I see is that the error message returned reports the URL as containing ORG-ID instead of the replaced value. The correct request including replaced ORG-ID is being generated for the request.


`org.jclouds.http.HttpResponseException: command: GET https://apidevlab1.opsourcecloud.net/oec/0.9/ORG-ID/server/0896551e-4fe3-4450-a627-ad5548e7e83a?clone=trevor-test2&desc=trevor-description2 HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`

Does this match your expectation?

**Comment by andreaturli** [comment]
Not sure I follow, looking at https://github.com/trevorflanagan/amp-dimensiondata/blob/ed9df833b56c4dcf1b246a3b1594278102bf8c2f/src/main/java/org/jclouds/dimensiondata/cloudcontroller/features/AccountApi.java#L34 it seems that you don't need ORG-ID there.

if that it's fine, you probably can remove the ORG-ID from [here](https://github.com/cloudsoft/amp-dimensiondata/blob/4dce31f2ca6652877b85d7e7ee86eb6c4a04e7bf/src/main/java/org/jclouds/dimensiondata/cloudcontroller/DimensionDataCloudControllerApiMetadata.java#L64-L64) and make the orgId complexity completely hidden in the impl using the `OrganisationIdFilter`

wdyt? I hope I'm not confusing your ideas

**Comment by trevorflanagan** [comment]
Correct the filter you suggest adding is not applicable to the AccountApi. 

It will be applicable to all of our other API's as they use ORG-ID as a PathParam. I just want to make sure that the @Path("/oec/0.9/**ORG-ID**") placeholder for ORG-ID is good with you? I will process the path in OrganisationIdFilter and replace ORG-ID there.

**Comment by andreaturli** [comment]
I'd personally try an implementation where there is no `ORG-ID` in any of the API's. Does it sound feasible?

**Comment by andreaturli** [comment]
just a general comment: wouldn't be better to work on different (smaller) PRs to simplify the review of those changes? Just a suggestion ...

**Comment by gatj98** [comment]
Sorry @andreaturli - we're github newbies and didn't realize we were adding more commits into the existing pull request by pushing to @trevorflanagan master branch.

**Comment by trevorflanagan** [comment]
Superseded by https://github.com/cloudsoft/amp-dimensiondata/pull/18

The remainder of the commits on this pull request will be split out once https://github.com/cloudsoft/amp-dimensiondata/pull/14 has been processed.

**Pull request closed without merging**
